name: Build Raeed Clinic Installer
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Compile with Inno Setup
        uses: lowlighter/py-inno-setup-action@v1.1
        with:
          filepath: "RaeedOPDClinic-Script.iss"

      - name: Upload Installer
        uses: actions/upload-artifact@v3
        with:
          name: Raeed-Clinic-Setup
          path: Output/*.exe
