name: Build Raeed Clinic Single EXE
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build EXE with PKG
        run: |
          npx pkg app.js --target node18-win-x64 --output RaeedClinic.exe
          
      - name: Upload Single EXE
        uses: actions/upload-artifact@v4
        with:
          name: Raeed-Clinic-Portable
          path: RaeedClinic.exe
